export enum OtpChannel {
	PHONE = 'PHONE'
};

export enum OtpPurpose {
	ACCOUNT_RECOVERY = 'ACCOUNT_RECOVERY',
	PASSWORD_RESET = 'PASSWORD_RESET',
	TWO_FACTOR_AUTHENTICATION = 'TWO_FACTOR_AUTHENTICATION'
};
